# Site
repository: hiyyijing.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yi Jing, Hong
#title: 職稱
email: hi.yyijing@gmail.com
#website: https://hiyyijing.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  hiyyijing
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: hiyyijing
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: github
  # icon: fas fa-github
  # url: https://github.com/hiyyijing
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! 我是洪宜靖，
  
  【學歷背景】國立中正大學 國際經濟研究所 碩士
  
  【專業背景】具備經濟與會計背景
  
  【培訓經歷】經濟部AI新秀人才培育專班：「金融創新×生成式AI」

#I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        link: https://ypysy.github.io/
        link_text: ypysy | 移工稅務 AI

#  - title: Education # Title for the section
  #  layout: list # Type of content section (list/text)
   # content:
    #  - layout: top-middle
     #   title: 國立中正大學
      #  sub_title: 國際經濟研究所 碩士

#  - title: Experience # Title for the section
 #   layout: list # Type of content section (list/text)
  #  content:
   #   - layout: left
    #    title: The Boring Company
     #   link: boringcompany.com
      #  # link_text: boringcompany.com
       # sub_title: Senior Network System Administrator
        #caption: November 2017 - Present
        #qote: >
         # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
       # description: | # this will include new lines to allow paragraphs
        #    Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

#  - title: A Little More About Me
 #   layout: text
  #  content: | # this will include new lines to allow paragraphs
   #   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
    #  - Rock climbing
     # - Gaming
      #- Knitting
     # - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

     # Look at this cool image  
     # ![Trees](/modern-resume-theme/images/landscape-trees.jpg)

# Footer
footer_show_references: true
# references_title: hi.yyijing/

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-remote-theme
